parameters:
#    syndic_comment.example.class: Syndic\CommentBundle\Example

services:
#    syndic_comment.example:
#        class: %syndic_comment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
