
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
            
_imagine:
    resource: .
    type:     imagine
    
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }
    
# fos_user_security:
    # resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#  
# fos_user_profile:
    # resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    # prefix: /profile
#  
# fos_user_register:
    # resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    # prefix: /register
#  
# fos_user_resetting:
    # resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    # prefix: /resetting
#  
# fos_user_change_password:
    # resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    # prefix: /change-password
#  

# Sonata User Bundle
sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile
 
soanata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

# Sonata Admin Bundle
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# import routes from a controller directory
syndic_main:
    resource: "@SyndicMainBundle/Controller"
    type:     annotation
