parameters:
#    syndic_main.example.class: Syndic\MainBundle\Example

services:
#    syndic_main.example:
#        class: %syndic_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
