parameters:
#    syndic_user.example.class: Syndic\UserBundle\Example

services:
#    syndic_user.example:
#        class: %syndic_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
